import { Customer } from '../service/cutomer';

export const customersData: Customer[] = [
  {
    id: '1',
    firstName: 'Mukul',
    lastName: 'Sharma',
    email: 'mukul.sharma@test.com',
    phone: '9876543210',
    address: '12 Rajpath',
    city: 'Delhi',
  },
  {
    id: '2',
    firstName: 'Riya',
    lastName: 'Kapoor',
    email: 'riya.kapoor@test.com',
    phone: '9876543211',
    address: '45 Marine Drive',
    city: 'Mumbai',
  },
  {
    id: '3',
    firstName: 'Aman',
    lastName: 'Verma',
    email: 'aman.verma@test.com',
    phone: '9876543212',
    address: '78 MG Road',
    city: 'Bengaluru',
  },
  {
    id: '4',
    firstName: 'Priya',
    lastName: 'Singh',
    email: 'priya.singh@test.com',
    phone: '9876543213',
    address: '23 Civil Lines',
    city: 'Jaipur',
  },
  {
    id: '5',
    firstName: 'Rahul',
    lastName: 'Mehta',
    email: 'rahul.mehta@test.com',
    phone: '9876543214',
    address: '9 Park Street',
    city: 'Kolkata',
  },
  {
    id: '6',
    firstName: 'Sneha',
    lastName: 'Patel',
    email: 'sneha.patel@test.com',
    phone: '9876543215',
    address: '17 SG Highway',
    city: 'Ahmedabad',
  },
  {
    id: '7',
    firstName: 'Karan',
    lastName: 'Malhotra',
    email: 'karan.malhotra@test.com',
    phone: '9876543216',
    address: '31 Sector 17',
    city: 'Chandigarh',
  },
  {
    id: '8',
    firstName: 'Neha',
    lastName: 'Joshi',
    email: 'neha.joshi@test.com',
    phone: '9876543217',
    address: '56 FC Road',
    city: 'Pune',
  },
  {
    id: '9',
    firstName: 'Arjun',
    lastName: 'Gupta',
    email: 'arjun.gupta@test.com',
    phone: '9876543218',
    address: '11 Hazratganj',
    city: 'Lucknow',
  },
  {
    id: '10',
    firstName: 'Ananya',
    lastName: 'Roy',
    email: 'ananya.roy@test.com',
    phone: '9876543219',
    address: '89 Salt Lake',
    city: 'Kolkata',
  },
  {
    id: '11',
    firstName: 'Vikram',
    lastName: 'Nair',
    email: 'vikram.nair@test.com',
    phone: '9876543220',
    address: '22 MG Road',
    city: 'Kochi',
  },
  {
    id: '12',
    firstName: 'Pooja',
    lastName: 'Yadav',
    email: 'pooja.yadav@test.com',
    phone: '9876543221',
    address: '64 Gomti Nagar',
    city: 'Lucknow',
  },
  {
    id: '13',
    firstName: 'Rohit',
    lastName: 'Bansal',
    email: 'rohit.bansal@test.com',
    phone: '9876543222',
    address: '101 Model Town',
    city: 'Ludhiana',
  },
  {
    id: '14',
    firstName: 'Isha',
    lastName: 'Arora',
    email: 'isha.arora@test.com',
    phone: '9876543223',
    address: '72 Residency Road',
    city: 'Jammu',
  },
  {
    id: '15',
    firstName: 'Siddharth',
    lastName: 'Khanna',
    email: 'siddharth.khanna@test.com',
    phone: '9876543224',
    address: '88 Ring Road',
    city: 'Indore',
  },
  {
    id: '16',
    firstName: 'Meera',
    lastName: 'Desai',
    email: 'meera.desai@test.com',
    phone: '9876543225',
    address: '13 Alkapuri',
    city: 'Vadodara',
  },
  {
    id: '17',
    firstName: 'Yash',
    lastName: 'Tiwari',
    email: 'yash.tiwari@test.com',
    phone: '9876543226',
    address: '45 MP Nagar',
    city: 'Bhopal',
  },
  {
    id: '18',
    firstName: 'Nisha',
    lastName: 'Chopra',
    email: 'nisha.chopra@test.com',
    phone: '9876543227',
    address: '67 Mall Road',
    city: 'Shimla',
  },
  {
    id: '19',
    firstName: 'Aditya',
    lastName: 'Rana',
    email: 'aditya.rana@test.com',
    phone: '9876543228',
    address: '19 Clock Tower',
    city: 'Dehradun',
  },
  {
    id: '20',
    firstName: 'Kavya',
    lastName: 'Mishra',
    email: 'kavya.mishra@test.com',
    phone: '9876543229',
    address: '36 Ashok Nagar',
    city: 'Kanpur',
  },
  {
    id: '21',
    firstName: 'Manish',
    lastName: 'Saxena',
    email: 'manish.saxena@test.com',
    phone: '9876543230',
    address: '90 Nehru Place',
    city: 'Delhi',
  },
  {
    id: '22',
    firstName: 'Tanya',
    lastName: 'Sethi',
    email: 'tanya.sethi@test.com',
    phone: '9876543231',
    address: '25 Banjara Hills',
    city: 'Hyderabad',
  },
  {
    id: '23',
    firstName: 'Harsh',
    lastName: 'Agarwal',
    email: 'harsh.agarwal@test.com',
    phone: '9876543232',
    address: '54 MI Road',
    city: 'Jaipur',
  },
  {
    id: '24',
    firstName: 'Simran',
    lastName: 'Gill',
    email: 'simran.gill@test.com',
    phone: '9876543233',
    address: '80 GT Road',
    city: 'Amritsar',
  },
  {
    id: '25',
    firstName: 'Dev',
    lastName: 'Pandey',
    email: 'dev.pandey@test.com',
    phone: '9876543234',
    address: '102 Cantonment',
    city: 'Varanasi',
  },
];

export interface Product {
  id: number;
  name: string;
  price: number;
}

export const PRODUCTS: Product[] = [
  { id: 1, name: 'Laptop', price: 55000 },
  { id: 2, name: 'Mouse', price: 500 },
  { id: 3, name: 'Keyboard', price: 1200 },
  { id: 4, name: 'Monitor', price: 9500 },
  { id: 5, name: 'Headphones', price: 2500 },
];

export const TAX_RATE = 0.18;
